require("user.config.spec")
require("user.config.keymaps")
require("user.config.options")
require("user.config.autocmds")

spec("user.lspconfig")
spec("user.lualine")
spec("user.catppuccin")
spec("user.treesitter")
spec("user.gitsigns")
spec("user.mason")
spec("user.cmp")
spec("user.nvimtree")
spec("user.none-ls")
spec("user.telescope")
spec("user.whichkey")
spec("user.autopairs")
spec("user.indent-blankline")
spec("user.dashboard")
spec("user.tmux-navigation")

require("user.lazy")
